[features]
seeds = false
skip-lint = false
[programs.localnet]
futureofwork = "6y4f4UTUv3gePUwHntXJPkLpwWHPpcb9Fx8efXm3JkSe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
